### ISSUE TITLE
Images haven't been compiled in app-header 2.0.4

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#21]
I'm using the following app-header version

`"@pearson-components/app-header": "2.0.4"`

And seems any of the images haven't been compiled.

![image](https://cloud.githubusercontent.com/assets/10680296/24739291/dd36a18e-1ab8-11e7-87b1-0836cbae2ad4.png)

**Comment by wyseguyonline** [comment]
Image files for the app-header aren't compiled with the code for the component on purpose.  For current users of the app-header, the expectation is that the image files are being copied to an images directory off the root of the app as part of the consuming app's build process.  I am currently reviewing your PR.
