### ISSUE TITLE
CSS modules seems not loaded when the app-header is imported as a commonjs module

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#28]
I have imported the app-header as follows.
```
import AppHeader from '@pearson-components/app-header';

/* .... */

let appHeader = new AppHeader(element, options);
```

And here is how it looks like,
![image](https://cloud.githubusercontent.com/assets/10680296/25264820/1159b2e2-2687-11e7-9868-d767c5264bf4.png)

Regards,
Dinuka

**Comment by dinukadesilva** [comment]
@wyseguyonline 

Seems this issue is due to https://github.com/webpack-contrib/sass-loader#problems-with-url

But, according to how this is now, is it not possible to use the AppHeader as a commonjs module. I'm trying to use this in a react project with webpack and ES6. And facing issue.

**Comment by wyseguyonline** [comment]
There are some static assets in the images folder that will need to be copied to into your project as part of your build process.  

Console is using the app-header just fine as it currently is released and is a react project using webpack and ES6.  I have not heard about teams having issues using the app-header as either a commonjs module or within react projects.

Here is what I found in the Console project for how they are getting the app-header working (understand that their build process is copying the static assets).

import '@pearson-components/app-header/build/dist.app-header';

...

const element = document.querySelector('body');
const setup = {
    session: 'session',
    user: { givenName: firstName },  //value instantiated within this function scope
    mode: 'Basic',
    consoleBaseUrl: window.location.origin,  //Console's main URL
    onLogout() {
      const piSession = window.piSession;

      if (piSession) {
        piSession.logout();  //this function part of the PI client side API
      }

      return redirectToLogin();  // this function declared elsewhere
    }
  };

  document.dispatchEvent(new CustomEvent('o.DOMContentLoaded', {
    detail: {
      element,
      config: setup
    }
  }));

**Comment by dinukadesilva** [comment]
@wyseguyonline 
Actually even I had followed the same way in our applications. And yes it works fine. 

As also there in the following example, my question is actually when I use the app-header as a commonjs module described in the readme as well. 
```
var AppHeader = require('@pearson-components/app-header');
var appHeader = new AppHeader(element, options);
```
And then only I'm facing the above issue.

**Comment by dinukadesilva** [comment]
I figured this is specific to my application and found this is working correctly.

Thanks @wyseguyonline

**Comment by wyseguyonline** [comment]
I built a test application using ES6 and Webpack and I am able to successfully import and instantiate the app-header component as a commonjs module.  I am unable to reproduce the results shown above.  I am using the following code in my test application:

```
import AppHeader from '@pearson-components/app-header';

const element = document.querySelector('body');
const setup = {
  session: 'session',
  user: { givenName: 'Jon' },
  mode: 'Basic',
  consoleBaseUrl: 'https://console.pearson.com',
  onLogout() {
    console.log('Logout Clicked!');
  }
};

const appHeader = new AppHeader(element, setup);
```
It might be that in using webpack and ES6 (which I assume means you're using something like Babel to transpile your code from ES6 to ES5), your use of require might be causing problems.  Try using import (as shown above) and see if that fixes things.

Apart from that, we will need you to provide the code, your webpack.config.js file, any and all webpack output, all Javascript console output if we are going to troubleshoot this issue further.

**Comment by dinukadesilva** [comment]
No issue @wyseguyonline . I could get this working perfect. The issue was in my application and i could get that sorted. And thank you very much.
