### ISSUE TITLE
Imported header requires reference to deprecated scss file

### ISSUE THREAD

**Issue by pglockwo** [Pearson-Higher-Ed/app-header#45]
After importing the header component into my react application I needed to reference the scss file here

'../../node_modules/'&#64;pearson-components'/app-header/main.scss'

which in one of the child imports required 

'node_modules/pearson-elements/scss/elements/color/_variables';

which is in the the deprecated version of Pearson Elements.

Do I need to reference the main.scss is there a way to make this work without having to include the deprecated version?

**Comment by mhomolak** [comment]
While Elements is deprecated, it is still being supported.  There are plans to rewrite the app-header as a React component and when that is done it will pull in the new Elements-SDK.  For the time being though, you should not feel hesitant about using the deprecated repo.
