### ISSUE TITLE
Adding application header to app header

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/app-header#49]
@mhomolak @wyseguyonline 

In most of the projects, the new headers have been changing to following format. Is there any road map in app-header to enable it. I mean adding the application title

![image](https://user-images.githubusercontent.com/10680296/40907357-2eef8c98-6801-11e8-827b-13480891d1f7.png)

**Comment by wyseguyonline** [comment]
The app-header and other UXF components are no longer under the direct planning or control of our team so I do not know what the future plans are for the app-header.  We have been moved on to another project.  This is a question best posed to @antelopeb (Greg Davis) and his team.  Greg, meet Dinuka.  Dinuka, meet Greg.

**Comment by Koshila-cd** [comment]
@mhomolak 

I get this error when I get a new clone and build it. Is there any way I can resolve it?

![screenshot from 2018-06-06 12-24-00](https://user-images.githubusercontent.com/35322940/41021600-a1be66ca-6984-11e8-940d-3db88e30de3e.png)

I got a new clone before the last five commits (before May 30, 2018) and it worked fine.

**Comment by antelopeb** [comment]
Fixed and released.
