### ISSUE TITLE
Error in a new clone

### ISSUE THREAD

**Issue by Koshila-cd** [Pearson-Higher-Ed/app-header#50]
@mhomolak @antelopeb 
I get this error when I get a new clone and build it. Is there any way I can resolve it?
I got a new clone before the last five commits (before May 30, 2018) and it worked fine.
![screenshot from 2018-06-06 12-24-00](https://user-images.githubusercontent.com/35322940/41022030-f9b58c36-6985-11e8-82b1-0667dd5f1fc7.png)

**Comment by mhomolak** [comment]
This does not appear to be an issue with the component but instead with your local machine.  That being said I was able to do a fresh clone and install on my local machine without any issues.  I was using node 6.9.1 and 8.1.1.

In addition to this Myself, @JasonLantz and @wyseguyonline are no longer on this project.  @antelopeb and his team have taken over and can handle any inquiries in the future.
