### ISSUE TITLE
Error when running test classes

### ISSUE THREAD

**Issue by Koshila-cd** [Pearson-Higher-Ed/app-header#51]
@antelopeb 
I get this error when I run "npm run test". Probably a npm versioning issue.
Also can I know the node and npm versions used when developing this?

![image](https://user-images.githubusercontent.com/35322940/41277777-d2250790-6e45-11e8-922c-bb5883378a99.png)

**Comment by antelopeb** [comment]
@davodey -- is this still an issue? Or can we close this one on app-header?

**Comment by davodey** [comment]
@antelopeb non issue.
